import Navigation from "../components/navigation"
import AboutUs from "./about-us/page"

export const metadata = {
  title: 'Wakawaka Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}

